/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: "#f7f9fb",
        tertiary: "#000000",
        "on-primary-fixed": "#131b2e",
        "on-surface": "#191c1e",
        "surface-container": "#eceef0",
        "surface-bright": "#f7f9fb",
        "input-active": "#2563EB",
        "on-secondary-fixed": "#00201d",
        "primary-container": "#131b2e",
        outline: "#76777d",
        error: "#ba1a1a",
        "on-primary-fixed-variant": "#3f465c",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "border-muted": "#E2E8F0",
        "currency-negative": "#DC2626",
        "on-secondary-container": "#006f66",
        "surface-dim": "#d8dadc",
        "on-secondary-fixed-variant": "#005049",
        "on-error-container": "#93000a",
        "secondary-container": "#86f2e4",
        "on-tertiary-container": "#76859b",
        "secondary-fixed-dim": "#6bd8cb",
        "currency-positive": "#059669",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#bec6e0",
        "tertiary-container": "#0d1c2f",
        "outline-variant": "#c6c6cd",
        "surface-container-highest": "#e0e3e5",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#0d1c2f",
        "surface-variant": "#e0e3e5",
        "on-primary-container": "#7c839b",
        "surface-container-low": "#f2f4f6",
        "primary-fixed-dim": "#bec6e0",
        "inverse-on-surface": "#eff1f3",
        "primary-fixed": "#dae2fd",
        secondary: "#006a61",
        "tertiary-fixed-dim": "#b9c7e0",
        primary: "#000000",
        surface: "#f7f9fb",
        "secondary-fixed": "#89f5e7",
        "on-tertiary-fixed-variant": "#3a485c",
        "on-secondary": "#ffffff",
        "on-background": "#191c1e",
        "inverse-surface": "#2d3133",
        "surface-tint": "#565e74",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#d5e3fd",
        "on-surface-variant": "#45464d"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        sm: "12px",
        xs: "8px",
        base: "4px",
        lg: "24px",
        xl: "32px",
        gutter: "16px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        md: "16px"
      },
      fontFamily: {
        "body-lg": ["Hanken Grotesk", "system-ui", "sans-serif"],
        "body-sm": ["Hanken Grotesk", "system-ui", "sans-serif"],
        "body-md": ["Hanken Grotesk", "system-ui", "sans-serif"],
        "headline-sm": ["Hanken Grotesk", "system-ui", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "system-ui", "sans-serif"],
        "label-caps": ["Hanken Grotesk", "system-ui", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "system-ui", "sans-serif"],
        "numeric-data": ["Hanken Grotesk", "system-ui", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "numeric-data": ["16px", { lineHeight: "24px", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
}